### ISSUE TITLE
Support feature to set base URL

### ISSUE THREAD

**Issue by sudheesh001** [sudheesh001/python-loklak-api#12]
With the number of loklak servers that are rising, and ability to have a personalized loklak server and vision to IOT.

Support setting of the base loklak URL.
- Set base loklak URL or use loklak.org
- Check if the base URL is working and live (enhancement, use hello)
  - fallback on failure to loklak.org
- set base URL and use it throughout.
  - Overwriting value parameter needed. (use env)

**Comment by daminisatya** [comment]
#16
